

platform :ios, '8.0'

target 'FBShareFile' do
   
   use_frameworks!
    pod 'FBShareSandbox', '~> 0.1.0'
    pod "GCDWebServer", "~> 3.0"
    pod "GCDWebServer/WebUploader", "~> 3.0"
    pod "GCDWebServer/WebDAV", "~> 3.0"
    
end
